export const employees = [
  {
    id: 1,
    name: 'John Doe',
    photo: 'https://avatar.iran.liara.run/public/1',
    role: 'Software Engineer',
    employment: 'Full-time',
    status: 'Present',
    checkIn: '09:00 AM',
    checkOut: '05:00 PM',
    overTime: '1h',
  },
  {
    id: 2,
    name: 'Jane Smith',
    photo: 'https://avatar.iran.liara.run/public/2',
    role: 'Product Manager',
    employment: 'Part-time',
    status: 'Present',
    checkIn: '09:00 AM',
    checkOut: '04:00 PM',
    overTime: '0h',
  },
  {
    id: 3,
    name: 'Alice Brown',
    photo: 'https://avatar.iran.liara.run/public/3',
    role: 'UX Designer',
    employment: 'Full-time',
    status: 'Late',
    checkIn: '11:30 AM',
    checkOut: '05:30 PM',
    overTime: '0h',
  },
  {
    id: 4,
    name: 'Mike Johnson',
    photo: 'https://avatar.iran.liara.run/public/4',
    role: 'Data Analyst',
    employment: 'Contract',
    status: 'Absent',
    checkIn: 'N/A',
    checkOut: 'N/A',
    overTime: '0h',
  },
  {
    id: 5,
    name: 'Emma Wilson',
    photo: 'https://avatar.iran.liara.run/public/5',
    role: 'QA Engineer',
    employment: 'Full-time',
    status: 'Present',
    checkIn: '09:00 AM',
    checkOut: '06:00 PM',
    overTime: '0.5h',
  },
  {
    id: 6,
    name: 'James Anderson',
    photo: 'https://avatar.iran.liara.run/public/6',
    role: 'DevOps Engineer',
    employment: 'Full-time',
    status: 'Absent',
    checkIn: 'N/A',
    checkOut: 'N/A',
    overTime: '0h',
  },
  {
    id: 7,
    name: 'Olivia Taylor',
    photo: 'https://avatar.iran.liara.run/public/7',
    role: 'HR Manager',
    employment: 'Part-time',
    status: 'Present',
    checkIn: '09:00 AM',
    checkOut: '03:30 PM',
    overTime: '0h',
  },
  {
    id: 8,
    name: 'Liam Thomas',
    photo: 'https://avatar.iran.liara.run/public/8',
    role: 'Finance Analyst',
    employment: 'Full-time',
    status: 'Late',
    checkIn: '11:00 AM',
    checkOut: '05:00 PM',
    overTime: '0h',
  },
  {
    id: 9,
    name: 'Sophia Martinez',
    photo: 'https://avatar.iran.liara.run/public/9',
    role: 'Marketing Specialist',
    employment: 'Contract',
    status: 'Present',
    checkIn: '09:00 AM',
    checkOut: '07:00 PM',
    overTime: '1h',
  },
  {
    id: 10,
    name: 'Benjamin Lee',
    photo: 'https://avatar.iran.liara.run/public/10',
    role: 'Sales Manager',
    employment: 'Full-time',
    status: 'Present',
    checkIn: '09:00 AM',
    checkOut: '06:30 PM',
    overTime: '0h',
  },
  {
    id: 11,
    name: 'Isabella Gonzalez',
    photo: 'https://avatar.iran.liara.run/public/11',
    role: 'Graphic Designer',
    employment: 'Part-time',
    status: 'Present',
    checkIn: '09:00 AM',
    checkOut: '06:00 PM',
    overTime: '0h',
  },
  {
    id: 12,
    name: 'Henry Robinson',
    photo: 'https://avatar.iran.liara.run/public/12',
    role: 'Content Writer',
    employment: 'Full-time',
    status: 'Absent',
    checkIn: 'N/A',
    checkOut: 'N/A',
    overTime: '0h',
  },
  {
    id: 13,
    name: 'Mia Clark',
    photo: 'https://avatar.iran.liara.run/public/13',
    role: 'Project Manager',
    employment: 'Full-time',
    status: 'Present',
    checkIn: '09:00 AM',
    checkOut: '04:00 PM',
    overTime: '0h',
  },
  {
    id: 14,
    name: 'Noah King',
    photo: 'https://avatar.iran.liara.run/public/14',
    role: 'Security Engineer',
    employment: 'Contract',
    status: 'Present',
    checkIn: '09:00 AM',
    checkOut: '03:00 PM',
    overTime: '2h',
  },
  {
    id: 15,
    name: 'Amelia Wright',
    photo: 'https://avatar.iran.liara.run/public/15',
    role: 'Business Analyst',
    employment: 'Full-time',
    status: 'Present',
    checkIn: '09:00 AM',
    checkOut: '05:30 PM',
    overTime: '0.5h',
  },
  {
    id: 16,
    name: 'Lucas Hill',
    photo: 'https://avatar.iran.liara.run/public/16',
    role: 'Database Administrator',
    employment: 'Full-time',
    status: 'Present',
    checkIn: '09:00 AM',
    checkOut: '05:00 PM',
    overTime: '1h',
  },
  {
    id: 17,
    name: 'Charlotte Scott',
    photo: 'https://avatar.iran.liara.run/public/17',
    role: 'Software Engineer',
    employment: 'Part-time',
    status: 'Present',
    checkIn: '09:00 AM',
    checkOut: '07:00 PM',
    overTime: '0h',
  },
  {
    id: 18,
    name: 'Daniel Green',
    photo: 'https://avatar.iran.liara.run/public/18',
    role: 'Systems Analyst',
    employment: 'Contract',
    status: 'Present',
    checkIn: '09:00 AM',
    checkOut: '04:00 PM',
    overTime: '0h',
  },
  {
    id: 19,
    name: 'Sofia Adams',
    photo: 'https://avatar.iran.liara.run/public/19',
    role: 'Recruiter',
    employment: 'Full-time',
    status: 'Present',
    checkIn: '09:00 AM',
    checkOut: '05:00 PM',
    overTime: '0.5h',
  },
  {
    id: 20,
    name: 'Mason Nelson',
    photo: 'https://avatar.iran.liara.run/public/20',
    role: 'Frontend Developer',
    employment: 'Full-time',
    status: 'Present',
    checkIn: '09:00 AM',
    checkOut: '05:30 PM',
    overTime: '0h',
  },
];
